import { ILeadRecord, ILeadSubmission } from './interfaces';

export const MOCK_LEAD_SUBMISSION: ILeadSubmission = {
    submittedOn: '2019-04-16',
    firstName: 'First1',
    lastName: 'Last1',
    email: 'someone@getnada.com',
    companyName: 'Company1',
    annualIncome: 101,
    debt: 1,
    industry: 'Industry1',
}

export const LEADS: ILeadRecord[] = [{
    createdOn: '2019-04-16',
    modifiedOn: '2021-04-23',
    firstName: 'Tanjiro',
    lastName: 'Kamado',
    email: 'hashira-in-training@demonslayer.com',
    companyName: 'Demon Slayer Corps',
    annualIncome: 100,
    debt: 5,
    industry: 'Sanitation',
}, {
    createdOn: '2013-12-02',
    modifiedOn: '2020-05-31',
    firstName: 'Rick',
    lastName: 'Sanchez',
    email: 'genius@wubbalubba.ww',
    companyName: 'Jerryboree',
    annualIncome: 1000000,
    debt: 0,
    industry: 'Engineering',
}, {
    createdOn: '1928-11-18',
    modifiedOn: '2021-05-03',
    firstName: 'Mickey',
    lastName: 'Mouse',
    email: 'theears@waltdisneyco.com',
    companyName: 'Steamboat Ferries',
    annualIncome: 99000000000,
    debt: 10000,
    industry: 'Entertainment',
}, {
    createdOn: '1958-09-07',
    modifiedOn: '2010-09-07',
    firstName: 'Walter',
    lastName: 'White',
    email: 'heisenberg@yahoo.com',
    companyName: 'Gray Matter Technologies',
    annualIncome: 7000000,
    debt: 52000,
    industry: 'Engineering',
}, {
    createdOn: '1965-03-15',
    modifiedOn: '2013-05-16',
    firstName: 'Michael',
    lastName: 'Scott',
    email: 'worldsbestboss@aol.com',
    companyName: 'Dunder Mifflin',
    annualIncome: 79900,
    debt: 200000,
    industry: 'Sales',
}, {
    createdOn: '1989-12-17',
    modifiedOn: '2021-05-23',
    firstName: 'Homer',
    lastName: 'Simpson',
    email: 'kwijibo@springfield.edu',
    companyName: 'Springfield Power Company',
    annualIncome: 24395.80,
    debt: 10000,
    industry: 'Engineering',
}, {
    createdOn: '2009-04-09',
    modifiedOn: '2015-02-24',
    firstName: 'Ron',
    lastName: 'Swanson',
    email: 'nunya@idontthinkso.org',
    companyName: 'Very Good Building and Development Company',
    annualIncome: 72100000,
    debt: 0,
    industry: 'Woodworking',
}, {
    createdOn: '2003-11-02',
    modifiedOn: '2019-03-15',
    firstName: 'George Oscar',
    lastName: 'Bluth',
    email: 'illusionist@aztectomb.com',
    companyName: 'The Alliance of Magicians',
    annualIncome: 0,
    debt: 25000,
    industry: 'Entertainment',
}, {
    createdOn: '1881-08-30',
    modifiedOn: '1997-06-30',
    firstName: 'Albus',
    lastName: 'Dumbledore',
    email: 'headmaster@horwarts.uk',
    companyName: 'Hogwarts',
    annualIncome: 250000,
    debt: 1,
    industry: 'Education',
}, {
    createdOn: '2011-04-17',
    modifiedOn: '2019-05-19',
    firstName: 'Jon',
    lastName: 'Snow',
    email: 'stark@thenorth.net',
    companyName: 'The Nights Watch',
    annualIncome: 100000,
    debt: 10000,
    industry: 'Military',
}];
